service: hai-nyt-puzzle

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  scraper:
    handler: main.run
    events:
      # Invoke Lambda function every day
      - schedule: rate(1 day)